name: Fetch latest data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'

jobs:
  download-data:
    name: Download latest quota data
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install dependencies
        uses: BSFishy/pip-action@v1
        with:
          requirements: requirements.txt

      - name: Get current date
        run: |
          echo "current_date=$(date +'%F')" >> $GITHUB_ENV

      - name: Run Python script
        run: python run.py quotas-${{ env.current_date }}.xlsx

      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: current-quota-balances.xlsx
          path: ./quotas-${{ env.current_date }}.xlsx

      - name: Create release
        uses: ncipollo/release-action@v1.8.4
        with:
          artifact: ./quotas-${{ env.current_date }}.xlsx 
          name: ${{ env.current_date }}
          commit: ${{ github.ref }}
          tag: ${{ env.current_date }}
          token: ${{ secrets.GITHUB_TOKEN }}
